/* HDDASHGEN.C (c) Markus Hoffmann  */

/* This file is part of MQTT-Hyperdash, the MQTT Dashboard 
 * ============================================================
 * MQTT-Hyperdash is free software and comes with NO WARRANTY - read the file
 * COPYING for details
 */
 
 /* This tool makes a series of generic .dash files out of a (sorted) list
    of topics, like the list created by mqtt-list-topics.
    
    A common way to create such a parameter tree is by excecuting
    mqtt-list-topics --broker localhost | sort | hddashgen --broker localhost

 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <ctype.h>
#include <fnmatch.h>
#include <dirent.h>
#include <string.h>
#include <sys/stat.h>
#if defined WINDOWS || defined ANDROID
  #define EX_OK 0
#else
  #include <sysexits.h>
#endif

#include "file.h"
#include "hddashgen.h"

#define DEFAULT_BROKER "tcp://localhost:1883"

int verbose=0;    /* Verbosity level */
char *broker_url=DEFAULT_BROKER;
char *broker_user=NULL;
char *broker_passwd=NULL;
char *dashboard_prefix="";

char *dashboarddir="."; /* by default use current dir.*/

static void hddashgen_set_defaults() {
  /* Set the default path where the .dash files are searched for. 
   * The path can be overridden by a commandline parameter.
   */
  char *envptr;
  static char path[256];
  envptr=getenv("HOME");
  if(envptr) {
    snprintf(path,sizeof(path),"%s/.hyperdash/dashboards",envptr);
    if(exist(path)) { /* It does exist! */
      dashboarddir=path;
    }
  }
}



static void intro() {
  puts("hddashgen " HDDASHGEN_VERSION " (c) 2020 by Markus Hoffmann\n"
         "This tool is part of MQTT-Hyperdash, the universal MQTT Dashboard for linux.");
}
static void usage() {
  printf(
    "\nUsage: %s [-hvq] ---\tcreate dashboards from topic lists.\n\n"
    "  -h --help\t\t---\tusage\n"
    "  --broker  <url>\t---\tdefine the broker url used [%s]\n"
    "  --user <user>\t\t--- use this username for broker.\n"
    "  --passwd <passwd>\t\t--- use this password for broker.\n"
    "  --dashpath <path>\t---\tset path for dash files [%s]\n"
    "  --prefix <name>\t---\tset prefix for dashboard file names [%s]\n"
    "  -v\t\t\t---\tbe more verbose\n"
    "  -q\t\t\t---\tbe more quiet\n"
    ,"hddashgen",broker_url,dashboarddir,dashboard_prefix);
}
static void kommandozeile(int anzahl, char *argumente[]) {
  int count,quitflag=0;
  /* process command line parameters */
  for(count=1;count<anzahl;count++) {
    if(!strcmp(argumente[count],"-h") || !strcmp(argumente[count],"--help")) {
      intro();
      usage();
      quitflag=1;
    } 
    else if(!strcmp(argumente[count],"--version"))  {
      intro();
      quitflag=1;
    } 
    else if(!strcmp(argumente[count],"--broker")) broker_url=argumente[++count];
    else if(!strcmp(argumente[count],"--user"))   broker_user=argumente[++count];
    else if(!strcmp(argumente[count],"--passwd")) broker_passwd=argumente[++count];
    else if(!strcmp(argumente[count],"--dashpath")) dashboarddir=argumente[++count];
    else if(!strcmp(argumente[count],"--prefix")) dashboard_prefix=argumente[++count];
    else if(!strcmp(argumente[count],"-v"))	  verbose++;
    else if(!strcmp(argumente[count],"-q"))	  verbose--;
    else if(*(argumente[count])=='-') ; /* do nothing, these could be options for the rule itself */
    else {
      /* do nothing, these could be options for rule itself */
    }
  }
  if(quitflag) exit(EX_OK);
}

typedef struct {
  char *name;
  char *typ;
  int anz;
  char *inhalt;
} TOPIC;

TOPIC topics[1000];
int anztopics=0;

#define advance() y+=30; \
	    if(y>560) {y=70;x+=250;} \
	    if(h<y+30) h=y+30; \
	    if(w<x+250) w=x+250


int do_level(int level,char *match, char *filename) {
  int i,offset=0;
  int x=5,y;
  char filenameprefix[256];
  char fullfilename[256];
  char buffer[128];
  char old[128];
  char *p1,*p2;
  int sublevel;
  int w=200;
  int h=100;
  *old=0;
  /* Open/create file */
  snprintf(filenameprefix, sizeof(filenameprefix),"%s%s",dashboard_prefix,filename);
  snprintf(fullfilename, sizeof(fullfilename),"%s/%s%s",dashboarddir,dashboard_prefix,filename);
  printf("--> %s [%s]\n",fullfilename,match);
  FILE *fp=fopen(fullfilename,"w");
  if(fp==NULL) {
    printf("ERROR: could not create %s\n",fullfilename);
    return(-1);
  }
  fprintf(fp,"PANEL: TITLE=\"%s\" W=%d H=%d FGC=$ffffffff BGC=$000040ff\n##############################\n",filename,w,h);
  fprintf(fp,"# generated by hddasghen " HDDASHGEN_VERSION "\n");
  if(broker_user) {
    fprintf(fp,"BROKER: URL=\"%s\" USER=\"%s\" PASSWD=\"%s\"\n",broker_url,broker_user,broker_passwd);
  } else fprintf(fp,"BROKER: URL=\"%s\"\n",broker_url);
  y=70;
  if(match) {
    offset=strlen(match);
    fprintf(fp,"TEXT: X=10 Y=30 FGC=$ffff00FF h=40 TEXT=\"%s\" FONT=\"Arial_Bold\" FONTSIZE=20\n",match);
    if(w<10+strlen(match)*14) w=10+strlen(match)*14;
  } else {
  
    fprintf(fp,"TEXT: X=10 Y=10 FGC=$ffffffFF h=20 TEXT=\"%s\" FONT=\"Arial_Bold\" FONTSIZE=20\n","Root of Broker");
    fprintf(fp,"TEXT: X=10 Y=30 FGC=$ffffffFF h=20 TEXT=\"%s\" FONT=\"Arial_Bold\" FONTSIZE=16\n",dashboard_prefix);
  
  
    /* Create a button for each *mainroot_hd.dash it finds. */
  
    DIR *dp;
    struct dirent *entry;
    struct stat statbuf;
  
    if((dp = opendir(dashboarddir)) == NULL) {
      fprintf(stderr,"cannot open directory: %s\n",dashboarddir);
    } else {
  
      while((entry = readdir(dp)) != NULL) {
        lstat(entry->d_name,&statbuf);
        if(S_ISDIR(statbuf.st_mode)) {
            /* Found a directory, but ignore . and .. */
            if(strcmp(".",entry->d_name) == 0 ||
                strcmp("..",entry->d_name) == 0)
                continue;
        } else {
	  if(!fnmatch("*mainroot_hd.dash",entry->d_name,FNM_NOESCAPE|FNM_PATHNAME)) {
            if(strcmp(entry->d_name,filenameprefix)) {
	      printf("%s\n",entry->d_name);
	      char buf[256];
	      char buf2[256];
	      strncpy(buf,entry->d_name,256);
	      strncpy(buf2,entry->d_name,256);
	      int l=strlen(buf);
	      if(l>=5) buf[l-5]=0;
	      if(l>16) buf2[l-16]=0;
	      fprintf(fp,"PBOX: X=%d Y=%d W=%d H=%d FGC=$808080ff BGC=$8080c0ff\n",x+5,y,180,20);
	      fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Arial\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buf2);
	      fprintf(fp,"FRAMETOGGLE: X=%d Y=%d W=%d H=%d\n",x+5,y,180,20);
	      fprintf(fp,"DASH: X=%d Y=%d W=%d H=%d DASH=\"%s\"\n",x+5,y,180,20,buf);
              fprintf(fp,"\n");
              advance();
	    }
	  }
        }
      }
      closedir(dp);
      y+=10;
    }
  }
  
  
  for(i=0;i<anztopics;i++) {
    if(match==NULL || !strncmp(topics[i].name,match,strlen(match))) {
      p1=&(topics[i].name[offset]);
    //  printf("Match: <%s>\n",p1);
      p2=buffer;
      sublevel=0;
      while(*p1 && *p1!='/') *p2++=*p1++; 
      if(*p1=='/') sublevel=1;
      *p2=0;
      if(strncmp(old,buffer,128)) {

	if(sublevel) {
	  /* Make a Button to follow the tree */
	  /* Process new branch*/
	  char newmatch[128];
	  if(match) snprintf(newmatch,sizeof(newmatch),"%s%s/",match,buffer);
	  else snprintf(newmatch,sizeof(newmatch),"%s/",buffer);
	  char nfilename[128];
	  p1=nfilename;
	  p2=newmatch;
	  while(*p2) {
	    if(*p2=='/') *p1='_';
	    else *p1=tolower(*p2);
	    p1++;
	    p2++;
	  }
	  *p1=0;
	  strcat(nfilename,"hd");
	  char text[256];
	  p1=text;
	  p2=newmatch;
	  while(*p2) {
	    if(*p2=='/' && p2[1]) p1=text;
	    else *p1++=*p2;
	    p2++;
	  }
	  if(p1>text) --p1;
	  *p1=0;
	  
	  char buf[256];
	  snprintf(buf,sizeof(buf),"%s%s",dashboard_prefix,nfilename);
	  fprintf(fp,"PBOX: X=%d Y=%d W=%d H=%d FGC=$808080ff BGC=$808080ff\n",x+5,y,180,20);
	  fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Arial\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,text);
	  fprintf(fp,"FRAMETOGGLE: X=%d Y=%d W=%d H=%d\n",x+5,y,180,20);
	  fprintf(fp,"DASH: X=%d Y=%d W=%d H=%d DASH=\"%s\"\n",x+5,y,180,20,buf);
          fprintf(fp,"\n");

	  strcat(nfilename,".dash");
	  do_level(level+1,newmatch,nfilename);

          advance();
	} else {
	  if(!strcmp(buffer,"ACTIVITY_DM")) {
	    fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buffer);
            fprintf(fp,"BITMAPLABEL: x=%d y=%d BGC=$000040ff TOPIC=\"%s\" "
                       "  BITMAP[0]=\"0|Disc1|$ffffffff\" \\\n" 
                       "  BITMAP[1]=\"1|Disc2|$ffffffff\" \\\n"
                       "  BITMAP[2]=\"2|Disc3|$ffffffff\" \\\n"
                       "  BITMAP[3]=\"3|Disc4|$ffffffff\" \n",x+160,y,topics[i].name);

	    advance();
	  } else if(!strcmp(buffer,"STATUS_DM")) {
	    fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buffer);
            fprintf(fp,"BITMAPLABEL: x=%d y=%d BGC=$000040ff TOPIC=\"%s\" "
                       "  BITMAP[0]=\"0|SmallCircle|$00ff00ff\" \\\n" 
                       "  BITMAP[1]=\"1|SmallCircle|$ff0000ff\" \\\n"
                       "  BITMAP[2]=\"2|SmallCircle|$ffff00ff\" \\\n"
                       "  BITMAP[3]=\"3|SmallCircle|$ff00ffff\" \n",x+160,y,topics[i].name);

            advance();
	  } else if(!strcmp(buffer,"STATUS_SM")) {
	    fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buffer);
	    fprintf(fp,"TOPICSTRING: X=%d Y=%d W=110 H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TOPIC=\"%s\" BGC=$00ff FGC=$ffff00ff\n",x+130,y,20,topics[i].name);
	    fprintf(fp,"FRAME: X=%d Y=%d W=%d H=%d REVERT=1\n",x+130-2,y-2,110+4,20+4);
            advance();
	    
	  } else if(!fnmatch("*_AM",buffer,FNM_NOESCAPE|FNM_PATHNAME)) {
	    fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buffer);
	    fprintf(fp,"TOPICNUMBER: X=%d Y=%d W=100 H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TOPIC=\"%s\" BGC=$40ff FGC=$ffff00ff FORMAT=\"######.###\"\n",x+150,y,20,topics[i].name);
            if(w<x+250) w=x+250;
            advance();
	  } else if(!fnmatch("*_AC",buffer,FNM_NOESCAPE|FNM_PATHNAME)) {
	    fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buffer);
	    fprintf(fp,"TOPICNUMBER: X=%d Y=%d W=100 H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TOPIC=\"%s\" BGC=$40ff FGC=$00ffffff FORMAT=\"######.###\"\n",x+150,y,20,topics[i].name);
            if(w<x+250) w=x+250;
            advance();
 
	    fprintf(fp,"PBOX:  X=%d Y=%d W=%d H=%d BGC=$808080ff\n",x+7,y,240,20);
	    fprintf(fp,"FRAME: X=%d Y=%d W=%d H=%d\n",x+7-2,y-2,240+4,20+4);
	    fprintf(fp,"FRAME: X=%d Y=%d W=%d H=%d REVERT=1\n",x+7-2+20,y+2,240+4-40,20-4-1);
	    fprintf(fp,"BITMAP: X=%d Y=%d BITMAP=\"TickLeft\" FGC=$ffffffff\n",x+7,y+2);
	    fprintf(fp,"BITMAP: X=%d Y=%d BITMAP=\"TickRight\" FGC=$ffffffff\n",x+7+220+2,y+2);
	    fprintf(fp,"HSCALER: X=%d Y=%d W=%d H=%d TOPIC=\"%s\" MIN=0 MAX=4 TIC=0.05 FGC=$808080ff BGC=$ff AGC=$0\n",x+7+20,y+2,240-40,20-4-2,topics[i].name);
	    fprintf(fp,"TICKER: X=%d Y=%d W=%d H=%d TOPIC=\"%s\" MIN=0 MAX=4 TIC=-0.05\n",x+7,    y+2,16,16,topics[i].name);
	    fprintf(fp,"TICKER: X=%d Y=%d W=%d H=%d TOPIC=\"%s\" MIN=0 MAX=4 TIC=0.05\n", x+7+220+2,y+2,16,16,topics[i].name);

            if(w<x+250) w=x+250;
            advance();
	  } else if(!fnmatch("*_DM",buffer,FNM_NOESCAPE|FNM_PATHNAME)) {
	    fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buffer);
	    fprintf(fp,"TOPICNUMBER: X=%d Y=%d W=100 H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TOPIC=\"%s\" BGC=$40ff FGC=$ffff00ff FORMAT=\"######\"\n",x+150,y,20,topics[i].name);
            if(w<x+250) w=x+250;
            advance();
	  } else if(!fnmatch("*_SM",buffer,FNM_NOESCAPE|FNM_PATHNAME)) {
	    fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buffer);
	    fprintf(fp,"TOPICSTRING: X=%d Y=%d W=110 H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TOPIC=\"%s\" BGC=$00ff FGC=$ffff00ff\n",x+130,y,20,topics[i].name);
	    fprintf(fp,"FRAME: X=%d Y=%d W=%d H=%d REVERT=1\n",x+130-2,y-2,110+4,20+4);
            advance();
	  } else if(!fnmatch("*_SC",buffer,FNM_NOESCAPE|FNM_PATHNAME)) {
	    fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buffer);
	    fprintf(fp,"TOPICSTRING: X=%d Y=%d W=110 H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TOPIC=\"%s\" BGC=$00ff FGC=$ffffff\n",x+130,y,20,topics[i].name);
	    fprintf(fp,"FRAME: X=%d Y=%d W=%d H=%d REVERT=1\n",x+130-2,y-2,110+4,20+4);
	    fprintf(fp,"TOPICINSTRING: X=%d Y=%d W=%d H=%d TOPIC=\"%s\"\n",x+150-2,y-2,100+4,20+4,topics[i].name);
            advance();

	  } else {
	    fprintf(fp,"TEXT: X=%d Y=%d H=%d FONT=\"Courier_New_Bold\" FONTSIZE=16 TEXT=\"%s\" FGC=$ffffffff\n",x+10,y,20,buffer);
	    if(!strcmp(topics[i].typ,"binary")) {
	      fprintf(fp,"TEXTAREA: X=%d Y=%d W=100 H=%d FONT=\"Courier_New_Bold\" FONTSIZE=10 TOPIC=\"%s\" BGC=$00ff FGC=$ff00ffff\n",x+150,y,20,topics[i].name);
	    } else {
	      fprintf(fp,"TEXTAREA: X=%d Y=%d W=100 H=%d FONT=\"Courier_New_Bold\" FONTSIZE=10 TOPIC=\"%s\" BGC=$00ff FGC=$ffffffff\n",x+150,y,20,topics[i].name);
	      fprintf(fp,"TOPICINSTRING: X=%d Y=%d W=%d H=%d TOPIC=\"%s\"\n",x+150-2,y-2,100+4,20+4,topics[i].name);
	    }
	    fprintf(fp,"FRAME: X=%d Y=%d W=%d H=%d REVERT=1\n",x+150-2,y-2,100+4,20+4);
  	    advance();
	  }
	}
      }
      strncpy(old,buffer,128);
    }
  }
  fprintf(fp,"TEXT: X=%d Y=%d FGC=$ffff00FF h=20 TEXT=\"%s\" FONT=\"Arial\" FONTSIZE=10\n",x+5,y+5,
  "generated by hddashgen V.1.0");
  
  rewind(fp);
  fprintf(fp,"PANEL: TITLE=\"%s\" W=%d H=%d FGC=$ffffffff BGC=$000040ff\n",filename,w,h);
  /* close file */
  fclose(fp);
  return(1);
}
#define next_column()     p1=p2; \
      while(*p1 && isspace(*p1)) p1++; \
      p2=p1; \
      while(*p2 && !isspace(*p2)) p2++; \
      *p2++=0


int main(int argc, char* argv[]) {
  hddashgen_set_defaults();     /* Set default dashboard directory. */
  kommandozeile(argc, argv);    /* process command line */

  /* Read from stdin */

    char *line = NULL; 
    char *p1,*p2;
    size_t size;
    while(getline(&line, &size, stdin) != -1) {
      p1=line;
      if(*p1==0) continue;
      while(*p1 && isspace(*p1)) p1++;
      if(*p1==0) continue;
      if(*p1=='#') continue;
      p2=p1;
      while(*p2 && !isspace(*p2)) p2++;
      *p2++=0;
      topics[anztopics].name=strdup(p1);

      next_column(); topics[anztopics].anz=atoi(p1);
      next_column(); topics[anztopics].typ=strdup(p1);
      next_column(); topics[anztopics].inhalt=strdup(p1);
      anztopics++;
    }
    free(line);
    
  printf("hddashgen: Have %d topics from list.\n",anztopics);
  do_level(0,NULL,"mainroot_hd.dash");
  return(EX_OK);
}
