.TH HYPERDASH 1 04-Jan-2019 "Version 1.02" "MQTT Hyperdash"
.SH NAME
hyperdash \- The MQTT dashboard interpreter 
.SH SYNOPSIS
.B hyperdash
.RI "[ " option " ] " 
.I <filename>

.SH DESCRIPTION

MQTT Hyperdash is a fast and efficient dashboard (GUI) for the MQTT framework. 

The man machine interface is the interactive tool from which the individual
components of the Internet of Things (IoT) are controlled. In order to avoid 
confusion and to minimize the learning time, the interface builds on ergonomic 
and logical concepts which allow for an intuitive understanding of its 
operation and of the operation of the devices it controls.

Virtual control panels (dashbors) allow users to operate on the graphical 
representations of a large set of devices like switches, knobs, sliders, 
digital and analog indicators, whose behaviour is equivalent to that of the 
real (and sometimes analog) instrumental devices. 
The connection with
the mosquitto broker on the lower layers is automatic
and completely transparent.


.SH Filenames

.B hyperdash
processes one input file. The suffix of the input file is 
usually .dash.

.SH OPTIONS
.TP
.BR \-q
Be quiet and print less debug information. 
.TP
.BR \-v
Be more verbose and print debug information. 
.TP
.BR \-\-version
shows version, program and other information and exits.
.TP
.BR \-h ", " \-\-help
print a short help and exit.
.TP
.BR \-\-broker " " \fIurl\fR
specify a broker url which will be used instead of the one define 
in the .dash file.
.TP
.BR \-\-prefix " " \fIprefix\fR
specify a prefix to all TOPICs defined in the .dash file.
.TP
.BR \-\-user " " \fIusername\fR
specify a username for the broker. This overrides the .dash file settings.
.TP
.BR \-\-passwd " " \fIpasswd\fR
specify a password for the broker. This overrides the .dash file settings.
.TP
.BR \-\-dashpath " " \fIpath\fR
specify a path where .dash files are to be searched. 
Hyperdash first seaches for the given filename in the current directory, if not
fond there, it looks into this specified directory. It defaults to 
$HOME/.hyperdash/dashboards if that exist and /usr/share/hyperdash/dashboards else.
.TP
.BR \-\-fontpath " " \fIpath\fR
specify a path where the true type fonts used by hyperdash are searched for. 
It defaults to /usr/share/fonts/truetype/msttcorefonts . 
.TP
.BR \-\-iconpath " " \fIpath\fR
specify a path where the icons (png files) used by hyperdash are searched for. 
It defaults to /usr/share/hyperdash/icons .
.TP
.BR \-\-bitmappath " " \fIpath\fR
specify a path where the bitmaps (monochrome) used by hyperdash are searched for. 
It defaults to /usr/share/hyperdash/bitmaps .
.TP
.BR \-\-fullscreen
enable fullscreen graphics mode.
.TP
.BR \-\-noopts
do not pass previous commandline options to sub-dashboards. Normally the path 
settings as well as the broker/user/passwd settings are passed to all 
sub-dashboards called from this instance. If you do not want this, you can
use --noopts as a last commandline option. It disables the passing of all 
options which have been set before. However, options passed after --noopts are passed
anyways.
.PP
For detailed help and description of the MQTT principle take a 
look at the README file coming with the package. 


.SH EXAMPLES
.nf
hyperdash main.dash &
.fi



.SH VERSION
Page was created for V.1.02

.SH BUG REPORTS       

If you find a bug in the MQTT hyperdash software, you should report it. But
first, you should make sure that it really is a bug, and that it appears in
the latest version of the MQTT-Hyperdash package that you have.

Once you have determined that a bug actually exists, mail a bug report to
kollo@users.sourceforge.net. If you have a fix, you are welcome to mail that
as well! Suggestions may be mailed to the bug tracking system.

Comments and bug reports concerning this manual page should be directed to
kollo@users.sourceforge.net.

.SH AUTHOR
Markus Hoffmann <kollo@users.sourceforge.net>

.SH COPYRIGHT
Copyright (C) 2019-2020 Markus Hoffmann 

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software 
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

.SH SEE ALSO
mosquitto(1), mosquitto_pub(1), mosquitto_sub(1), mqtt-list-topics(1)
