.TH MQTT-LIST-TOPICS 1 04-Jan-2020 "Version 1.00" "MQTT Hyperdash"
.SH NAME
mqtt-list-topics \- List all (retined) topics on a mqtt broker. 
.SH SYNOPSIS
.B mqtt-list-topics
.RI "[ " options " ] "

.SH DESCRIPTION

mqtt-list-topics connects to a mqtt broker and listens for a 
certein amount of time (default 1 second) for all topics available. A list will
pe printed to stdout. 

mqtt-list-topics also performs a brief analysis on the topics content to 
classify the topic into binary, string, number, and integer. This 
classification is not perfect, since it is based on a single payload value only, 
but it can help making automatic dashboards for MQTT-Hyperdash. 

.SH OPTIONS
.TP
.BR \-q
Be quiet and print less debug information. 
.TP
.BR \-v
Be more verbose and print debug information. 
.TP
.BR \-\-broker " " \fIurl\fR
specify the broker url. By default "tcp://localhost:1883" is used. 
.TP
.BR \-\-user " " \fIusername\fR
specify a username for the broker.
.TP
.BR \-\-passwd " " \fIpasswd\fR
specify a password for the broker. 
.TP
.BR \-\-pattern " " \fIpattern\fR
specify a topic pattern. By default "#" is used. 
.TP
.BR \-\-wait " " \fIseconds\fR
specify a time to wait/listen in seconds. By default, the time is 1 second. 
.TP
.BR \-\-version
shows version, program and other information and exits.
.TP
.BR \-h ", " \-\-help
print a short help and exit.
.PP
For detailed help and description of the MQTT principle take a 
look at the README file coming with the package. 


.SH EXAMPLES
.nf
mqtt-list-topics --wait 0 --broker "tcp://localhost:1883"
.fi



.SH VERSION
Page was created for V.1.02

.SH BUG REPORTS       

If you find a bug in the MQTT Hyperdash software, you should report it. But
first, you should make sure that it really is a bug, and that it appears in
the latest version of the MQTT-Hyperdash package that you have.

Once you have determined that a bug actually exists, mail a bug report to
kollo@users.sourceforge.net. If you have a fix, you are welcome to mail that
as well! Suggestions may be mailed to the bug tracking system.

Comments and bug reports concerning this manual page should be directed to
kollo@users.sourceforge.net.

.SH AUTHOR
Markus Hoffmann <kollo@users.sourceforge.net>

.SH COPYRIGHT
Copyright (C) 2019-2020 Markus Hoffmann 

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software 
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

.SH SEE ALSO
mosquitto(1), mosquitto_pub(1), mosquitto_sub(1), hyperdash(1)
